# render.yaml
services:
  - type: web
    name: api-nest-ecommerce
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    env: node
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/TU_USUARIO/TU_REPO
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: TU_URL_POSTGRESQL
