# render.yaml
# Archivo para que Render levante automáticamente tu NestJS y tu base de datos PostgreSQL

services:
  - type: web
    name: api-nest-ecommerce
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    env: node
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/TU_USUARIO/TU_REPO
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: db-ecommerce
          property: connectionString

  - type: psql
    name: db-ecommerce
    plan: free
    region: oregon